# Generated by Django 5.0.6 on 2024-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_treat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('finches', models.ManyToManyField(related_name='toys', to='main_app.finch')),
            ],
        ),
        migrations.DeleteModel(
            name='Treat',
        ),
    ]
